trivial: fix a gir generation error
```
../libfwupd/fwupd-security-attr-private.h:24: Error: Fwupd: multiple "Since:" tags for identifier "FWUPD_SECURITY_ATTR_ID_PREBOOT_DMA_PROTECTION":
 * Since: 1.8.0 (for all vendors)
   ^
```